import { DomainClientUser, type PingResult } from "./domain-client-user";
import { DomainClientError, type ErrorCode } from "./domain-client-error";
import {
  GraphQLTransport,
  type Transport,
  type SignHandler,
  type RequestContext,
  type ResponseContext,
} from "./transport";
import { RestTransport } from "./rest-transport";

export type GlobalErrorHandler = (error: DomainClientError) => void;
export type PongHandler = (status: PingResult) => void;

export interface DomainHostClientOptions {
  /**
   * API endpoint URL.
   * - GraphQL: e.g. "/graphql" (single endpoint for all operations)
   * - REST:    e.g. "http://localhost:5000" (base URL, paths appended)
   */
  endpoint?: string;
  /**
   * Transport protocol type.
   * - `"graphql"` (default) — Uses GraphQLTransport, POSTs GraphQL documents.
   * - `"rest"` — Uses RestTransport, maps operations to RESTful HTTP.
   */
  transportType?: "graphql" | "rest";
  /** URL path prefix for REST transport (default: "/api"). Only applies when transportType="rest". */
  restPathPrefix?: string;
  /** Explicit URL path overrides for REST transport. Only applies when transportType="rest". */
  restUrlMap?: Record<string, string>;
  /**
   * V4.9.19: REST query field names that should send GET + JSON body.
   * Passed through to `RestTransport.explicitBodyQueries`.
   * Only applies when transportType="rest".
   */
  restExplicitBodyQueries?: ReadonlySet<string>;
  /**
   * Storage implementation for session key persistence.
   *
   * Options:
   * - `sessionStorage` (default) — Session-scoped, cleared when tab closes.
   * - `localStorage` — Survives tab close and browser restart.
   * - Memory storage (automatic SSR fallback) — Implemented when sessionStorage
   *   is unavailable.
   * - Custom Storage — Any object implementing the `Storage` interface:
   *   `{ getItem(key): string|null; setItem(key,value): void; removeItem(key): void; }`
   */
  storage?: Storage;
  /** Retry configuration, default 3 attempts with exponential backoff */
  retry?: {
    maxAttempts?: number;
    baseDelaySeconds?: number;
    maxDelaySeconds?: number;
    jitter?: boolean;
    retryOn?: ErrorCode[];
  };
  /**
   * Map of GraphQL field names to their subfield selection strings.
   * Generated by codegen (`operationSelection` in domain-client.g.ts).
   * When provided, Use() proxies automatically append selection
   * to every object-typed request — required for HotChocolate compliance.
   */
  selectionMap?: Record<string, string>;
  /**
   * V4.5: 默认使用安全登录（Challenge-Response）。
   * true:  loginAs() 内部自动走 loginSecure()
   * false: loginAs() 走原有 loginByPassword()（明文过 SSL）
   * 默认: true
   */
  useSecureLogin?: boolean;
}

export class DomainHostClient {
  private storageKey: string;
  private endpoint: string;
  private transportType: "graphql" | "rest";
  private restPathPrefix?: string;
  private restUrlMap?: Record<string, string>;
  private restExplicitBodyQueries?: ReadonlySet<string>;
  private storage?: Storage;
  private retry?: DomainHostClientOptions["retry"];
  private selectionMap?: Record<string, string>;
  private useSecureLogin: boolean;
  private signHandler?: SignHandler;
  private globalErrorHandler?: GlobalErrorHandler;
  private pongInterval?: number;
  private pongHandler?: PongHandler;
  private pongTimer?: ReturnType<typeof setTimeout>;
  private abortController?: AbortController;
  private isBrowser: boolean;

  private onRequestHandler?: (
    req: RequestContext,
  ) => void | RequestContext | Promise<RequestContext | void>;
  private onResponseHandler?: (
    res: ResponseContext,
    req: RequestContext,
  ) => void;

  private constructor(
    storageKey: string,
    options?: DomainHostClientOptions,
  ) {
    this.storageKey = storageKey;
    this.endpoint = options?.endpoint ?? "/graphql";
    this.transportType = options?.transportType ?? "graphql";
    this.restPathPrefix = options?.restPathPrefix;
    this.restUrlMap = options?.restUrlMap;
    this.restExplicitBodyQueries = options?.restExplicitBodyQueries;
    this.storage = options?.storage;
    this.retry = options?.retry;
    this.selectionMap = options?.selectionMap;
    this.useSecureLogin = options?.useSecureLogin ?? true;
    this.isBrowser =
      typeof window !== "undefined" && typeof document !== "undefined";
  }

  /** Create a DomainHostClient instance */
  static init(
    storageKey: string,
    options?: DomainHostClientOptions,
  ): DomainHostClient {
    return new DomainHostClient(storageKey, options);
  }

  /** Register custom request signing handler */
  onSign(handler: SignHandler): this {
    this.signHandler = handler;
    return this;
  }

  /** Register global error handler (Use() uncaught error sink) */
  onGlobalError(handler: GlobalErrorHandler): this {
    this.globalErrorHandler = handler;
    return this;
  }

  /**
   * Register heartbeat monitoring.
   * Pings only when user is active (keyboard/mouse events).
   * No-op in SSR environments.
   *
   * @param intervalMinutes - Interval in minutes. Minimum: 1. Recommended: 5.
   *   Use 0 or omit to disable heartbeat.
   * @param handler - Callback receiving pong status on each successful ping.
   */
  onPong(intervalMinutes: number, handler: PongHandler): this {
    this.pongInterval = Math.max(1, intervalMinutes);
    this.pongHandler = handler;
    return this;
  }

  /** Register request interceptor */
  onRequest(
    handler: (
      req: RequestContext,
    ) => void | RequestContext | Promise<RequestContext | void>,
  ): this {
    this.onRequestHandler = handler;
    return this;
  }

  /** Register response interceptor */
  onResponse(
    handler: (res: ResponseContext, req: RequestContext) => void,
  ): this {
    this.onResponseHandler = handler;
    return this;
  }

  /** Get authenticated user.
   *  Reads session from storage. Throws DomainClientError('AUTH_REQUIRED') if no session found.
   */
  GetUser(): DomainClientUser {
    const transport = this.createTransport();
    const user = new DomainClientUser({
      transport,
      storage: this.storage,
      storageKey: this.storageKey,
      selectionMap: this.selectionMap,
      useSecureLogin: this.useSecureLogin,
    });

    const restored = user.restore();
    if (!restored) {
      throw new DomainClientError(
        "No session found. User is not authenticated.",
        "AUTH_REQUIRED",
      );
    }

    // V4.8.7: 注册全局错误处理器
    if (this.globalErrorHandler) {
      user.onGlobalError(this.globalErrorHandler);
    }
    this.startHeartbeat(user);
    return user;
  }

  /** Create a guest user (anonymous, no session) */
  GetGuest(): DomainClientUser {
    const transport = this.createTransport();
    const user = new DomainClientUser({
      transport,
      storage: this.storage,
      storageKey: this.storageKey,
      selectionMap: this.selectionMap,
      useSecureLogin: this.useSecureLogin,
    });
    // V4.8.7: 注册全局错误处理器
    if (this.globalErrorHandler) {
      user.onGlobalError(this.globalErrorHandler);
    }
    return user;
  }

  // ── V4.5 Convenience methods ──

  /**
   * V4.5: 一行代码登录。
   * 自动创建 Guest 用户，根据 useSecureLogin 选项选择安全或明文路径。
   */
  async loginAs(userName: string, password: string): Promise<import("./domain-client-user").LoginPayload> {
    return this.GetGuest().loginAs(userName, password);
  }

  /**
   * V4.5: 一行代码安全注册。
   * 自动生成 salt → PBKDF2 → 提交到服务端。
   */
  async registerSecure(userName: string, password: string): Promise<import("./domain-client-user").RegisterResult> {
    return this.GetGuest().registerSecure(userName, password);
  }

  /**
   * Release all resources.
   * Call during component unmount or app shutdown.
   *
   * Actions:
   * - Clears heartbeat timers
   * - Aborts pending requests
   * - Releases internal references
   *
   * React: `useEffect(() => { return () => host.dispose(); }, [])`
   * Safe to call multiple times — subsequent calls are no-ops.
   */
  dispose(): void {
    this.stopHeartbeat();
    this.abortController?.abort();
    this.globalErrorHandler = undefined;
    this.pongHandler = undefined;
    this.signHandler = undefined;
  }

  /** Access the global error handler (for Use/Call proxy) */
  getGlobalErrorHandler(): GlobalErrorHandler | undefined {
    return this.globalErrorHandler;
  }

  private createTransport(): Transport {
    const defaultRetry = { maxAttempts: 3, baseDelaySeconds: 1, maxDelaySeconds: 10, jitter: true, retryOn: ["NETWORK_ERROR", "SERVER_ERROR"] as ErrorCode[] };
    const opts = {
      url: this.endpoint,
      signHandler: this.signHandler,
      onRequest: this.onRequestHandler,
      onResponse: this.onResponseHandler,
      retry: this.retry ? { ...defaultRetry, ...this.retry } : undefined,
    };

    if (this.transportType === "rest") {
      return new RestTransport({
        ...opts,
        pathPrefix: this.restPathPrefix,
        urlMap: this.restUrlMap,
        explicitBodyQueries: this.restExplicitBodyQueries,
      });
    }

    return new GraphQLTransport(opts);
  }

  private startHeartbeat(user: DomainClientUser): void {
    if (!this.pongInterval || !this.pongHandler || !this.isBrowser) return;

    const intervalMs = this.pongInterval * 60 * 1000;
    let lastActivity = Date.now();
    const activityEvents = [
      "keydown",
      "mousemove",
      "mousedown",
      "scroll",
      "touchstart",
    ];

    const onActivity = (): void => {
      lastActivity = Date.now();
    };
    for (const evt of activityEvents) {
      window.addEventListener(evt, onActivity, { passive: true });
    }

    const tick = async (): Promise<void> => {
      const idle = Date.now() - lastActivity;
      if (idle < intervalMs * 2) {
        try {
          const status = await user.ping();
          if (status) this.pongHandler!(status);
        } catch {
          // ping failed silently
        }
      }
      this.pongTimer = setTimeout(tick, intervalMs);
    };

    this.pongTimer = setTimeout(tick, intervalMs);
  }

  private stopHeartbeat(): void {
    if (this.pongTimer) {
      clearTimeout(this.pongTimer);
      this.pongTimer = undefined;
    }
  }
}
